#!/usr/bin/env bash
usage() {
  echo -n "
get-request METRIC URL

Get specific information from a web request.

Possible METRICs:

  time
  The total time the request took in milliseconds.

  server-time
  The server response time (time to first byte) in milliseconds.

  @TODO: size code body headers etc

Examples

  get-request time https://www.google.com
  get-request server-time https://www.google.com

"
}

if [[ $# -lt 2 ]]; then
  usage
  exit 1
fi

METRIC=$1
URL=$2

case $METRIC in
  time)
    curl -s -o /dev/null -w '%{time_total}' "$URL" | awk '{printf "%.0f\n", $1 * 1000}'
    ;;
  server-time)
    curl -s -o /dev/null -w '%{time_starttransfer}' "$URL" | awk '{printf "%.0f\n", $1 * 1000}'
    ;;
  *)
    echo "Unknown metric: $METRIC"
    usage
    exit 1
    ;;
esac
