name: Test GitHub action
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  DEBUG: yes

jobs:
  
  install-scripts:
    name: Test GitHub Action
    runs-on: ubuntu-latest
    steps:

    - uses: jonpugh/goatscripts@v1
      with:
        path: .custom/goatscripts
    
    - run: run-with-summary ls -la .custom/goatscripts
      env:
        SUCCESS: "goatscripts directory"
        SUMMARY: |
          This is a test of the goatscripts github action. The action simply installs the scripts and sets the path so you can use them immediately.
          Use this file as an example to install and use the scripts.

    - run: run-with-summary which run-with-summary
      env:
        SUCCESS: "run-with-summary is installed."
        
    - run: run-with-summary curl https://api.github.com/
      env:
        SUCCESS: GitHub API is active
        ERROR: GitHub API unavailable!
