name: Test GitHub action
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  
  install-scripts:
    name: Run GitHub Action
    runs-on: ubuntu-latest
    steps:

    - uses: jonpugh/goatscripts@main
      with:
        path: .custom/goatscripts
    
    - run: run-with-summary ls -la .custom/goatscripts
      env:
        SUCCESS: "goatscripts directory"
        SUMMARY: |
          This is a test of the goatscripts github action. The action simply installs the scripts and sets the path so you can use them immediately.
          Use this file as an example to install and use the scripts.

    - run: run-with-summary which run-with-summary
      env:
        SUCCESS: "run-with-summary is installed."
        DEBUG: yes
        
    - run: run-with-summary curl https://api.github.com/
      env:
        SUCCESS: GitHub API is active
        ERROR: GitHub API unavailable!


  test-scripts:
    name: Test GitHub Action
    runs-on: ubuntu-latest
    steps:
    - uses: jonpugh/goatscripts@main
    - run: run-with-summary echo "Run With Summary successfully completed."
      env:
        SUCCESS: "Testing run-with-summary complete :boom:"
        SUMMARY: |
          This is a test of the run-with-summary script. 
          
          You can add any *markdown* you **like**, using the SUMMARY env var.

          For more details, check out [run-with-summary](https://github.com/jonpugh/goatscripts/blob/main/src/run-with-summary) source.
