name: Test GitHub action
on:
  pull_request:
    branches:
    - main

env:
  DEBUG: yes
  SUCCESS: "GOAT Scripts installed successfully."
  SUMMARY: |
    This is a test of the goatscripts github action. The action simply installs the scripts and sets the path so you can use them immediately.
    Use this file as an example to install and use the scripts.

jobs:
  
  install-scripts:
    name: Test GitHub Action
    runs-on: ubuntu-latest
    steps:

    - uses: jonpugh/goatscripts@SHA
      with:
        path: .custom/goatscripts
    
    - run: |
        run-with-summary ls -la .custom/goatscripts

    - run: run-with-summary which run-with-summary
      env: 
        SUCCESS: "run-with-summary is installed."
