# Test the scripts.

on:
  pull_request:
    branches:
    - main

jobs:
  
  run-with-summary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: run-with-summary
      env:
        SUCCESS: "Pinging Google Passed"
        FAILURE: "Ping Failed"
        SUMMARY: yes
        FILE: report-${{ github.run_id }}.md
      run: |
        ./src/run-with-summary ping w3.org -c5
        ls -la $FILE
        cat $FILE >> $GITHUB_STEP_SUMMARY
