# Test the scripts.

on:
  pull_request:
    branches:
    - main

jobs:
  
  run-with-summary:
    runs-on: ubuntu-latest
    env:
      FILE: report-${{ github.run_id }}.md

    steps:
    - uses: actions/checkout@v4
    - name: run-with-summary
      env:
        SUCCESS: "Pinging Google Passed"
        FAILURE: "Ping Failed"
        SUMMARY: yes
      run: |
        set -eo pipefail
        ./src/run-with-summary ping w3.org -c5
        exit_code=$?
        cat $FILE >> $GITHUB_STEP_SUMMARY
        exit $exit_code
