# Test the scripts.

on:
  pull_request:
    branches:
    - main

jobs:
  
  run-with-summary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: run-with-summary 
      run: |
        ./src/run-with-summary ping google.com -5
