# Test the scripts.
name: Run with Summary
on:
  pull_request:
    branches:
    - main

# Settings for run-with-summary script.
env:
  SUCCESS: "Script run-with-summary succeeded! :white_check_mark:"
  ERROR: "run-with-summary Failed! :x:"
  SUMMARY: |
    - Environment: https://pr${{ github.event.number }}.demo.site
    - Pull Request: ${{github.event.pull_request.html_url }}

  # Print summary in output logs
  SHOW: yes

  # Show extra details
  DEBUG: yes

  # Allow running run-with-summary command.
  PATH: ./src:./bin:./vendor/bin:/usr/local/bin:/usr/bin:/bin

jobs:
  
  run-with-summary:
    name: run-with-summary success
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: run-with-summary
      run: |
        run-with-summary ls -la
        run-with-summary $(env|grep GITHUB_)

  run-with-summary-fail:
    name: run-with-summary failure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: run-with-summary failure
      continue-on-error: true
      env:
        ERROR: "run-with-summary Failed on purpose! :x:"
      run: |
        echo $GITHUB_STEP_SUMMARY
        run-with-summary ping w3.org -c5
