# Test the scripts.

on:
  pull_request:
    branches:
    - main

jobs:
  
  run-with-summary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: run-with-summary
      env:
        SUCCESS: "Pinging Google Passed"
        FAILURE: "Ping Failed"
        SUMMARY: yes
      run: |
        ./src/run-with-summary ping google.com -n5
